### ISSUE TITLE
'ParseMode' has no attribute 'MARKDOWN_V2'

### ISSUE THREAD

**Issue by alamia442** [LivingWithHippos/unchained-bot#2]
2020-07-10 01:14:48,060 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/idfl/.local/share/virtualenvs/unchained-bot-haa2SKMF/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 390, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/idfl/.local/share/virtualenvs/unchained-bot-haa2SKMF/lib/python3.7/site-packages/telegram/ext/handler.py", line 117, in handle_update
    return self.callback(update, context)
  File "unchained-bot.py", line 202, in check_file
    parse_mode=telegram.ParseMode.MARKDOWN_V2)
AttributeError: type object 'ParseMode' has no attribute 'MARKDOWN_V2'

**Comment by LivingWithHippos** [comment]
The error is telling me that MARKDOWN_V2 is not found in ParseMode, I think it hasn't been added a lot of time ago.

Can you check if you're running the latest `python-telegram-bot` version (12.8 right now)?

Also tell me which install instruction are you following (pip, requirements etc.)
If you're using pip you can run `pip show python-telegram-bot`, I get

```
Name: python-telegram-bot
Version: 12.8
...
```

edit: I'll update pipenv because I can see that the lock file has the 12.4.2 version hardcoded (rightly so)
edit2: remove unchaindb before using the latest update

**Comment by LivingWithHippos** [comment]
I've also added a Dockerfile to ease the installation process so if you know docker you can use that

**Comment by LivingWithHippos** [comment]
Issue should be solved
